IMAGE_WIDTH = 150
IMAGE_HEIGHT = 150
NUM_CHANNELS = 3
INPUT_SHAPE = (IMAGE_WIDTH, IMAGE_HEIGHT, NUM_CHANNELS)
IMAGE_EXTENSION = "jpg"

BATCH_SIZE = 4
TRAIN_TRIPLES = 64
VALID_PAIRS = 300
EPOCHS = 12
EMBEDDING_SIZE = 3
MARGIN = 0.5
LR = 0.0001
